config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :posts

  devise_for :users
  resources :users do
    member do
      post 'follow/:following_id' => 'users#follow', as: :follow
      delete 'unfollow/:following_id' => 'users#unfollow', as: :unfollow
    end
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, class_name: 'User', foreign_key: :follower_id, primary_key: :id
  belongs_to :following, class_name: 'User', foreign_key: :following_id, primary_key: :id
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  validates :username, presence: true, length: { maximum: 30 }

  has_many :post, dependent: :destroy
  has_many :follower_users, class_name: 'Follow', foreign_key: :following_id
  has_many :following_users, class_name: 'Follow', foreign_key: :follower_id
  has_many :followers, through: :follower_users, source: :follower
  has_many :followings, through: :following_users, source: :following
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :create, :update, :destroy,]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post.user, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :create, :update, :destroy, :follow, :unfollow]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow]

  def index
    @users = User.all
  end

  def show
    @posts = Post.where(user: @user)
    @post = Post.new
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follow
    following = User.find(params[:following_id])
    @user.followings << following
    redirect_to following
  end

  def unfollow
    following = User.find(params[:following_id])
    @user.followings.delete(following)
    redirect_to following
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microblog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="sticky">
<nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to "MICROblog", root_url %>
      </h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
      <li class="has-dropdown active user-menu">
        <a href="#">
          <strong><%= current_user.username %></strong>
        </a>
          <ul class="dropdown">
            <li>
              <%= link_to 'Edit profile', edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
      </li>
      <% else %>
      <li class="active">
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li class="active">
        <%= link_to "Login", new_user_session_path %>
      </li>
      <% end %>
    </ul>
  </section>
</nav>
</div>

<div class="container">
  <% if notice %>
  <div class="alert-box">
    <%= notice %>
    <a class="close" href="">×</a>
  </div>
  <% end %>
  <% if alert %>
  <div class="alert-box warning">
    <%= alert %>
    <a class="close" href="">×</a>
  </div>
  <% end %>
<%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user_id %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="row">
<ul class="large-block-grid-5">
  <% @users.each do |user| %>
      <li class="user-card">
        <div class="light-blue">
          <img src="" alt="profile picture" class="picture"/>
        </div>
        <div class="profile">
          <%= link_to user.username, user %>
        </div>
      </li>
  <% end %>
</ul>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="profile">
  <div class="row">
    <div class="large-3 columns">
      <div class="row sidebar">
        <%= @user.username %>
        <%= link_to 'Edit', edit_user_path(@user) %>
      </div>
    </div>
    <div class="large-9 columns">
      <div class="large-12 columns">
        <%= render 'posts/form' %>
      </div>
      <div class="large-12 columns">
        <ul class="large-block-grid-5">
          <% @posts.each do |post| %>
              <li class="post-card">
                <div class="light-blue">
                  <p>
                    <%= post.content %>
                  </p>
                </div>
                <div class="permalink">
                  <%= link_to 'Permalink', post %>
                </div>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>